import { Document, HeadingLevel, Packer, Paragraph, TextRun } from "docx";
import type { Citation } from "@/lib/retrieval/verify";

export interface ExportSection {
  heading: string;
  text: string;
  citations: Citation[];
}

/**
 * Word export (§B8, acceptance criterion 6): editable document with a
 * citations appendix so source references survive the export.
 */
export async function buildExportDocx(params: { title: string; sections: ExportSection[] }): Promise<Buffer> {
  const children: Paragraph[] = [new Paragraph({ text: params.title, heading: HeadingLevel.HEADING_1 })];

  for (const section of params.sections) {
    children.push(new Paragraph({ text: section.heading, heading: HeadingLevel.HEADING_2 }));
    for (const para of section.text.split(/\n{2,}/)) {
      children.push(new Paragraph({ children: [new TextRun(para.replace(/\n/g, " "))] }));
    }
  }

  const allCitations = params.sections.flatMap((s, i) =>
    s.citations.map((c) => ({ section: s.heading, sectionIndex: i + 1, ...c })),
  );
  if (allCitations.length > 0) {
    children.push(new Paragraph({ text: "Sources and citations", heading: HeadingLevel.HEADING_2 }));
    for (const c of allCitations) {
      children.push(
        new Paragraph({
          children: [
            new TextRun({
              text: `[${c.sectionIndex}.${c.n}] ${c.filename} — wave ${c.wave}` +
                `${c.segmentName ? ` · ${c.segmentName}` : ""}` +
                `${c.interviewRef ? ` · interview ${c.interviewRef}` : ""}` +
                ` · ${c.evidenceType.replace(/_/g, " ")}` +
                `${c.sectionPath ? ` · ${c.sectionPath}` : ""}`,
              size: 18,
            }),
          ],
        }),
      );
    }
  }

  children.push(
    new Paragraph({
      children: [
        new TextRun({
          text: "Generated by the Consumer Sentiment Intelligence Hub. AI-assisted draft grounded in archive evidence — review before client use.",
          italics: true,
          size: 16,
        }),
      ],
    }),
  );

  const doc = new Document({ sections: [{ children }] });
  return Packer.toBuffer(doc);
}
